/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.contentassist.ide;

import org.eclipse.xtext.ui.tests.editor.contentassist.ContentAssistNoTerminalExtensionTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.editor.contentassist.ContentAssistNoTerminalExtensionTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ContentAssistNoTerminalExtensionTestLanguageIdeSetup extends ContentAssistNoTerminalExtensionTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ContentAssistNoTerminalExtensionTestLanguageRuntimeModule(), new ContentAssistNoTerminalExtensionTestLanguageIdeModule()));
	}
	
}
