/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.contentassist.ide;

import org.eclipse.xtext.ui.tests.editor.contentassist.ParametersTestLanguageExRuntimeModule;
import org.eclipse.xtext.ui.tests.editor.contentassist.ParametersTestLanguageExStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ParametersTestLanguageExIdeSetup extends ParametersTestLanguageExStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ParametersTestLanguageExRuntimeModule(), new ParametersTestLanguageExIdeModule()));
	}
}
