/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.contentassist.ide;

import org.eclipse.xtext.ui.tests.editor.contentassist.UnorderedGroupsTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.editor.contentassist.UnorderedGroupsTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class UnorderedGroupsTestLanguageIdeSetup extends UnorderedGroupsTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UnorderedGroupsTestLanguageRuntimeModule(), new UnorderedGroupsTestLanguageIdeModule()));
	}
}
