/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.enumrules.ide;

import org.eclipse.xtext.ui.tests.enumrules.EnumRulesUiTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.enumrules.EnumRulesUiTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EnumRulesUiTestLanguageIdeSetup extends EnumRulesUiTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EnumRulesUiTestLanguageRuntimeModule(), new EnumRulesUiTestLanguageIdeModule()));
	}
}
