/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.outline.ide;

import org.eclipse.xtext.ui.tests.editor.outline.OutlineTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.editor.outline.OutlineTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OutlineTestLanguageIdeSetup extends OutlineTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OutlineTestLanguageRuntimeModule(), new OutlineTestLanguageIdeModule()));
	}
}
