/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.ide;

import org.eclipse.xtext.ui.tests.FoldingTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.FoldingTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FoldingTestLanguageIdeSetup extends FoldingTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FoldingTestLanguageRuntimeModule(), new FoldingTestLanguageIdeModule()));
	}
}
