/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.testlanguages.ide;

import org.eclipse.xtext.ui.tests.testlanguages.ReferenceGrammarUiTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.testlanguages.ReferenceGrammarUiTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReferenceGrammarUiTestLanguageIdeSetup extends ReferenceGrammarUiTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReferenceGrammarUiTestLanguageRuntimeModule(), new ReferenceGrammarUiTestLanguageIdeModule()));
	}
}
