/*
 * generated by Xtext
 */
package org.eclipse.xtext.ui.tests.editor.encoding.ide;

import org.eclipse.xtext.ui.tests.editor.encoding.EncodingUiTestLanguageRuntimeModule;
import org.eclipse.xtext.ui.tests.editor.encoding.EncodingUiTestLanguageStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EncodingUiTestLanguageIdeSetup extends EncodingUiTestLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EncodingUiTestLanguageRuntimeModule(), new EncodingUiTestLanguageIdeModule()));
	}
}
